<a href="https://colab.research.google.com/github/alfredoaguiararce/Denavit-Hartenberg-Python/blob/main/Cinematica_Directa_(D_H).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Método de Denavit-Hartenberg**

---

El siguiente programa muestra la obtencion de matrices de rotacion por el método de **Denavit-Hartenberg**.

Este algoritmo ha sido desarrollado como parte del curso de la materia de Robotica, por **Alfredo Aguiar Arce**

[Adjunto mi repositorio de github](https://)


**1.- Se importan las liberias necesarias para calculos matriciales y representacion simbolica de variables.**

In [90]:
import numpy as np
import math
import sympy as sp
from sympy.solvers import solve

**2.- Se declaran las variables simbolicas a utilizar en caso de ser necesario.**

In [91]:
init_printing()
q_1,q_2,l_1 = symbols("q_1, q_2,l_1")

**3.- Funciones para obetner las matrices de rotacion de sobre cada eje siendo.**

*   Rx = Rotacion en eje X.
*   Rz = Rotacion en eje Z.


In [92]:
def Rx(alfai):
  """
  Rotacion en X
  Rx = Rotacion alrededor del eje Xi-1 un angulo Alfa subinice i.
  alfai = Angulo Alfa subindice i. 
  """
  Rx = np.array([[1,0,0,0],
                 [0,sp.cos(alfai),-sp.sin(alfai),0],
                 [0,sp.sin(alfai),sp.cos(alfai),0],
                 [0,0,0,1]])
  return Rx

def Rz(Omegai):
  """
  Rotacion en Z
  Rz = Rotacion alrededor del eje Zi-1 un angulo Omega subinice i.
  Oi = Angulo Omega subindice i.
  """
  Rz = np.array([[sp.cos(Omegai),-sp.sin(Omegai),0,0],
                 [sp.sin(Omegai),sp.cos(Omegai),0,0],
                 [0,0,1,0],
                 [0,0,0,1]]) 
  return Rz

**4.-Funciones para obtener las matrices de traslacion en cada plano.**


*   Tx = Traslacion a lo largo de X.
*   Tz = Traslacion a lo largo de Z.



In [93]:
def Tx (ai):
  """
    Tx = Translacion a lo largo de Xi-1 una distancia ai, Vector ai(ai,0,0)
    ai = distancia ai
  """
  Tx = np.array([[1,0,0,ai],
               [0,1,0,0],
               [0,0,1,0],
               [0,0,0,1]])
  return Tx

def Tz(di):
  """
  Tz = Translacion a lo largo de Zi-1 una distancia di, Vector di(0,0,di)
  di = distancia di
  """
  Tz = np.array([[1,0,0,0],
                 [0,1,0,0],
                 [0,0,1,di],
                 [0,0,0,1]])
  return Tz

**5.- Método por cinematica directa**

In [107]:
def CinematicaDirectaDH(DH):
  """
    Esta funcion regressa una matriz homogenea DH
    Donde : 
      DH = Matriz DH que pasamos.
      [H] = La matriz que se regresa al terminar las operaciones.
  """

  #Esta matriz evita que el algoritmo no funcione la primra vez que es ejecutado
  dimension = (4,4)
  A = np.ones(a); #Se crea una matriz identidad de n*n es decir 4 columnas RZ,TZ,TX,RX
  
  for i in range(len(DH)):
      #Denavit-HerHartenberg
      print('Matriz A')
      print(i)
      A = A * (Rz(DH[i][0])*Tz(DH[i][1])*Tx(DH[i][2])*Rx(DH[i][3]));
      print(A);

**6.- Implementación.**

In [108]:
#Se define la matriz de los parametros optenidos para este caso:
DH = np.array([[q_1 + (math.pi/2),0,0,math.pi/2],
               [0, l_1 + q_2,0,0]])
#Imprimimos para comprobar que se encuentre como deseamos la matriz
print(f"La matriz de Denavit-H, a evaluar es {DH}")

#Llamos a la funcion CinematicaDirectaDH() para obtener el resultado
CinematicaDirectaDH(DH)

La matriz de Denavit-H, a evaluar es [[q_1 + 1.5707963267949 0 0 1.5707963267948966]
 [0 l_1 + q_2 0 0]]
Matriz A
0
[[1.0*cos(q_1 + 1.5707963267949) 0 0.0 0.0]
 [0 6.12323399573677e-17*cos(q_1 + 1.5707963267949) 0 0.0]
 [0.0 0 6.12323399573677e-17 0.0]
 [0.0 0.0 0.0 1.0]]
Matriz A
1
[[1.0*cos(q_1 + 1.5707963267949) 0 0.0 0.0]
 [0 6.12323399573677e-17*cos(q_1 + 1.5707963267949) 0 0.0]
 [0.0 0 6.12323399573677e-17 0]
 [0.0 0.0 0.0 1.0]]
